version: "2.1"
services:

  app_test:
    container_name: app_test
    environment:
      - environment_type=test
    build:
      context: .
      dockerfile: Dockerfile-test
    command: >
      sh -c "alembic upgrade head &&
             pytest tests -v"
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - test_db

  test_db:
    image: postgres:latest
    container_name: test_db
    env_file:
      - .env.test
    volumes:
      - db_test:/var/lib/postgresql/data

volumes:
  db_test:
