version: "2.1"
services:

  backend:
    container_name: app
    build: ./
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:


